import type { Metadata } from 'next';
import { Barlow, Fraunces, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const fraunces = Fraunces({
  variable: '--font-fraunces',
  weight: ['900'],
  subsets: ['latin'],
});

const barlow = Barlow({
  variable: '--font-barlow',
  weight: ['500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fraunces.variable} ${barlow.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
